### ISSUE TITLE
请增加新的 API 接口！！！

### ISSUE THREAD

**Issue by OldFriend697688** [cat-bucket/cat-osint#4]
请务必增加新的 API 接口，老旧的 API 接口轰炸力度不够大。！！！

**Comment by OldFriend697688** [comment]
或者请提供抓取新接口的思路也可以

**Comment by cat-bucket** [comment]
多开几个session力度就差不多了 这个API不是我在维护 维护的人已经跑路了

**Comment by cat-bucket** [comment]
我跟你说 短信轰炸 实话实话你怎么轰炸 别人就算想告你 也就是没有什么实质损失 基本不会有什么影响 但是你要是自己去爬取接口 问题就大了 你自己查一下爬取敏感接口 在大陆是什么罪 API维护和我没有关系 不是我不会 是不敢
