### ISSUE TITLE
完全寄了用不了

### ISSUE THREAD

**Issue by Ark-Schwarz** [cat-bucket/cat-osint#5]
用asnycrun并发线程输入手机号后提示Error: Value must be an iterable.
普通run现在获取接口直接报错

**Comment by cat-bucket** [comment]
?  不会呀 我还又去试了一下

**Comment by Ark-Schwarz** [comment]
> ?  不会呀 我还又去试了一下

看了下脚本，是更新接口的问题，不更新就没事了，更新接口拿到的网址已经寄了，不过asyncrun那段代码我感觉没实际意义

**Comment by cat-bucket** [comment]
那个是为了说明 已经配置好环境了
